language: python
python:
  - "3.6"
  # - "3.5"
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script: pytest --cov=<PARAM: package_name>
after_success: coveralls
